edit CMakeLists.txt
Use glfw, glew, glm from brew if it's MacOS.
Also, following executables are exclude :
* tutorial17_rotations
* misc05_picking_slow_easy
* misc05_picking_custom
* misc05_picking_BulletPhysics

Because following error occurs :
Undefined symbols for architecture arm64:
  "_NSCalibratedWhiteColorSpace", referenced from:
      CTwMgr::PixmapCursor(int) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
  "_OBJC_CLASS_$_NSBitmapImageRep", referenced from:
       in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
  "_OBJC_CLASS_$_NSCursor", referenced from:
       in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
  "_OBJC_CLASS_$_NSImage", referenced from:
       in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
  "_OBJC_CLASS_$_NSString", referenced from:
       in libANTTWEAKBAR_116_OGLCORE_GLFW.a[2](LoadOGL.mm.o)
  "___CFConstantStringClassReference", referenced from:
       in libANTTWEAKBAR_116_OGLCORE_GLFW.a[2](LoadOGL.mm.o)
  "_objc_alloc", referenced from:
      NSGLGetProcAddressNew(unsigned char const*) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[2](LoadOGL.mm.o)
      NSGLCoreGetProcAddressNew(unsigned char const*) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[3](LoadOGLCore.mm.o)
      CTwMgr::PixmapCursor(int) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::PixmapCursor(int) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::PixmapCursor(int) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
  "_objc_autorelease", referenced from:
      CTwMgr::PixmapCursor(int) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::PixmapCursor(int) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
  "_objc_msgSend", referenced from:
       in objc-stubs-file
  "_objc_release", referenced from:
      NSGLGetProcAddressNew(unsigned char const*) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[2](LoadOGL.mm.o)
      NSGLCoreGetProcAddressNew(unsigned char const*) in libANTTWEAKBAR_116_OGLCORE_GLFW.a[3](LoadOGLCore.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::FreeCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      ...
  "_objc_retain", referenced from:
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      CTwMgr::CreateCursors() in libANTTWEAKBAR_116_OGLCORE_GLFW.a[8](TwMgr.mm.o)
      ...
ld: symbol(s) not found for architecture arm64